definitions:
  controllers.Card:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
      status:
        description: |-
          Status of the error
          in: int64
        type: integer
    type: object
  controllers.HTTPError:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
      status:
        description: |-
          Status of the error
          in: int64
        type: integer
    type: object
info:
  contact: {}
paths:
  /cards:
    get:
      consumes:
      - application/json
      description: Get  a list of cards
      parameters:
      - description: New Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/controllers.Card'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Card'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Get  a list of cards
      tags:
      - /cards
    post:
      consumes:
      - application/json
      description: Create a new card item
      parameters:
      - description: New Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/controllers.Card'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Card'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Create a card
      tags:
      - /cards
  /cards/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a new card item
      parameters:
      - description: New Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/controllers.Card'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Card'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Delete a card
      tags:
      - /cards
    get:
      consumes:
      - application/json
      description: Get a new card item
      parameters:
      - description: New Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/controllers.Card'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Card'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Get a card
      tags:
      - /cards
    put:
      consumes:
      - application/json
      description: Update a new card item
      parameters:
      - description: New Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/controllers.Card'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Card'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Update a card
      tags:
      - /cards
swagger: "2.0"
